/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Main
 * Method:    dotProduct
 * Signature: ([J[J)J
 */
JNIEXPORT jlong JNICALL Java_Main_dotProduct
  (JNIEnv *, jclass, jlongArray, jlongArray);

/*
 * Class:     Main
 * Method:    dotProductCritical
 * Signature: ([J[J)J
 */
JNIEXPORT jlong JNICALL Java_Main_dotProductCritical
  (JNIEnv *, jclass, jlongArray, jlongArray);

/*
 * Class:     Main
 * Method:    dotProductConsume
 * Signature: ([J[JLMain/Callback;)V
 */
JNIEXPORT void JNICALL Java_Main_dotProductConsume
  (JNIEnv *, jclass, jlongArray, jlongArray, jobject);

/*
 * Class:     Main
 * Method:    counterNew
 * Signature: (LMain/Callback;)J
 */
JNIEXPORT jlong JNICALL Java_Main_counterNew
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Main
 * Method:    counterInc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Main_counterInc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Main
 * Method:    counterDes
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Main_counterDes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Main
 * Method:    asyncComputation
 * Signature: (LMain/Callback;)V
 */
JNIEXPORT void JNICALL Java_Main_asyncComputation
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
